### ISSUE TITLE
Typescript error if trying to combine only one epic ...

### ISSUE THREAD

**Issue by JalilArfaoui** [thebrodmann/deox#100]
First, thanks for this very neat library !

Here's a weird error when used with redux-observable ... if trying to `combineEpics` only one epic !

I know `combineEpics` is useless with only one epic ... but if you have 2 epics, and you want to momentary disable one, it shouldn't be a problem IHMO. 

I've reproduced the issue based one the example given in the docs : https://deox.js.org/faq#using-redux-observable-with-deox

Here's my CodeSandbox "fork" : https://codesandbox.io/s/redux-observable-example-4g1lt

The only thing I changed from the given one (https://codesandbox.io/s/redux-observable-example-z6sdk) is to replace `combineEpics(fetchAllTodosEpic, addTodoEpic)` by `combineEpics(addTodoEpic)` in todos.ts. 

The error then pops all the way in create-store.ts on `epicMiddleware.run(rootEpic)` : 

```
(alias) const rootEpic: (action$: Observable<{
    type: "TODO_ADD_NEXT";
    payload: {
        title: string;
        completed: any;
    };
} | {
    type: "TODO_ADD_ERROR";
} | {
    type: "TODO_ADD_ERROR";
    payload: any;
    error: true;
} | {
    type: "TODO_ADD_ERROR";
    payload: any;
} | {
    ...;
} | {
    ...;
}>, _state$: Observable<...>, { api }: {
    ...;
}) => Observable<...>
import rootEpic
L'argument de type '(action$: Observable<{ type: "TODO_ADD_NEXT"; payload: { title: string; completed: any; }; } | { type: "TODO_ADD_ERROR"; } | { type: "TODO_ADD_ERROR"; payload: any; error: true; } | { type: "TODO_ADD_ERROR"; payload: any; } | { ...; } | { ...; }>, _state$: Observable<...>, { api }: { ...; }) => Observable<...>' n'est pas attribuable au paramètre de type 'Epic<Action<any>, Action<any>, void, { api: typeof import("/sandbox/src/store/api"); }>'.
  Les types des paramètres '_state$' et 'state$' sont incompatibles.
    Impossible d'assigner le type 'StateObservable<void>' au type 'Observable<{ todos: Todo[]; isFetching: boolean; }>'.
      Les types de la propriété 'operator' sont incompatibles.
        Impossible d'assigner le type 'Operator<any, void>' au type 'Operator<any, { todos: Todo[]; isFetching: boolean; }>'.
          Impossible d'assigner le type 'void' au type '{ todos: Todo[]; isFetching: boolean; }'.ts(2345)
```

Any insight on this ?

**Comment by JalilArfaoui** [comment]
Or do you think this is a pure `redux-observable` typing issue ?

**Comment by thebrodmann** [comment]
Hey @JalilArfaoui, Thank you for your trust and contribution.
I don't see any error on codesandbox!

![Screen Shot 2019-07-12 at 12 14 35 AM](https://user-images.githubusercontent.com/20781126/61080321-0de9df00-a43a-11e9-96d0-82a64f34464f.png)

**Comment by JalilArfaoui** [comment]
As I said, the error pops in create-store.ts on `epicMiddleware.run(rootEpic)` :

![image](https://user-images.githubusercontent.com/3037833/61083262-9319c780-a42b-11e9-8c0f-b3284a83d002.png)

**Comment by thebrodmann** [comment]
Oh, all of my error finding nuclei in my brain was searching around `combineEpic`.

It's related to https://github.com/redux-observable/redux-observable/issues/592.
The error is due to the default `void` type for the state generic in `EpicMiddleware` interface in `redux-observable` (maybe it was intentional!). I have provided a [codesandbox](https://codesandbox.io/s/redux-observable-type-issue-xd9rd) with simple epic to explain it.

**Comment by creaux** [comment]
Any workaround here?

**Comment by thebrodmann** [comment]
It's related to redux-observable @creaux
