### ISSUE TITLE
Add ofType rxjs operator

### ISSUE THREAD

**Issue by thebrodmann** [thebrodmann/deox#11]
In `redux-observable` there is an operator that is a higher order operator for the filter operator but it only can get an action type and doesn't work with action creators. In deox we should export an operator for this job that works correctly with both `action type`, `action` and `action creator`.

## Possible Implementation

```ts
import { filter } from 'rxjs/operators'

const ofType = <TC extends ActionCreator | AnyAction | string>(typeContainer: TC) => {
  const targetType = typeof typeContainer === 'string' ? typeContainer : getType(typeContainer)

  return filter(({ type }) => type === targetType)
}
```

**Comment by irmantaszenkus** [comment]
Is adding `rxjs` as a dependency brings value to this project? Maybe it could come as a separate package like `deox/ofType`?
