### ISSUE TITLE
How it will lead with react-hooks?

### ISSUE THREAD

**Issue by LukasTsunami** [thebrodmann/deox#116]
I liked a lot it but now that there is a new coding approach with Hooks, how Deox will lead with it

Thanks, and congratulations by the library

**Comment by thebrodmann** [comment]
Deox helps you create your Redux store more efficiently. React hooks changed the connect portion of `react-redux` API and it didn't affect your Redux store. So you can use Deox with react hooks like how you used it with `connect` higher-order component.
Also, you can check this [codesandbox](https://codesandbox.io/s/redux-observable-example-042ov?fontsize=14&module=%2Fsrc%2Fapp.tsx) to see a working example and you can compare it with [its previous](https://codesandbox.io/s/redux-observable-example-z6sdk?fontsize=14&module=%2Fsrc%2Fapp.tsx) version which is working by `connect` HOC.
