### ISSUE TITLE
ofType does no longer automatically infer action type in pipe

### ISSUE THREAD

**Issue by eXaminator** [thebrodmann/deox#141]
After upgrading to from 2.1.4 to 3.2.0 my epics are broken.

Before the update the `ofType` operator was able to infer the action type for the following operators in the pipe. It seems this no longer works.

This is the error I get after the update:

![image](https://user-images.githubusercontent.com/2758908/71990841-69075d80-3234-11ea-99cf-f2fde7188517.png)

This is the matching action creator:

![image](https://user-images.githubusercontent.com/2758908/71990628-057d3000-3234-11ea-8c1b-c91f5c6e10ac.png)

`switchMap` should be able to infer the type of the action and thus the types of the payload and meta properties.

Edit: I can also confirm that this works in 3.1.0.

**Comment by thebrodmann** [comment]
Hi @eXaminator. I tried to repro the issue in [CodeSandbox](https://codesandbox.io/s/patient-bash-0f9r5?fontsize=14&hidenavigation=1&theme=dark) but I wasn't able. What is the type of `action$`?

**Comment by eXaminator** [comment]
I can't test it now, but it might actually be a problem with the type of my action$ observable.

It's also `Observable<Action>`, but in my case `Action` is the default type from redux, not the specific action type. I will be able to check that tomorrow when I'm back to work.

But, nevertheless, I actually think it's more correct the "old" way, because before I apply the `ofType` filter `action$` can (and will) contain any action. So I think the behavior of 3.1.0, where `ofType` automatically infers the correct type based on the given action or action creator is the preferred behavior.

I forked your sandbox and updated it to match my version, which works with 3.1.0: https://codesandbox.io/s/deox141-cu3c6

**Comment by thebrodmann** [comment]
No repro works on [CodeSandbox](https://codesandbox.io/s/deox141-8ulql?fontsize=14&hidenavigation=1&theme=dark). Thank you @eXaminator for reporting this bug.

**Comment by eXaminator** [comment]
Thank YOU @thebrodmann for fixing it! :)
