### ISSUE TITLE
ESLint explicit-function-return-type rule error

### ISSUE THREAD

**Issue by VictorienT** [thebrodmann/deox#150]
When using as specified in doc : 

```ts
import { createActionCreator } from 'deox'

const reset = createActionCreator('RESET', resolve => (count: number) =>
  resolve(count)
)
```
the [explicit-function-return-type](https://github.com/typescript-eslint/typescript-eslint/blob/v2.21.0/packages/eslint-plugin/docs/rules/explicit-function-return-type.md) rule is reported on the `(count: number) => ` function.

How that should be handled?

**Comment by thebrodmann** [comment]
It's related to ESLint. You can disable this rule for a code blocks you want as follows.

```ts
/* eslint-disable explicit-function-return-type */
const reset = createActionCreator('RESET', resolve => (count: number) =>
  resolve(count)
)
/* eslint-enable explicit-function-return-type */
```

**Comment by VictorienT** [comment]
Hi, thanks for your prompt response!
Yeah I do know it's related to ESLint, I was wondering if there were a way to get the explicit return type rather than just disabling the rule.

**Comment by thebrodmann** [comment]
The purpose of this library is to reduce some redundant type verbosity.
BTW, if you want it, here you go:

```ts
import { Action } from 'deox'

const reset = createActionCreator('RESET', resolve => (count: number): Action<'RESET', number> =>
  resolve(count)
)
```

**Comment by VictorienT** [comment]
Nice, thank you!
