### ISSUE TITLE
Async and dispatch clarification

### ISSUE THREAD

**Issue by magneticflux-** [thebrodmann/deox#17]
I don't fully understand how to implement asynchronous actions or dispatch more actions from a handler. Could you clarify this in document?

**Comment by thebrodmann** [comment]
Hi, I think you are questioning about usage of deox with thunk. Am I right?

**Comment by magneticflux-** [comment]
Yes, or with another similar middleware such as `redux-promise`. How do they interact with the handler-list-creator function?

**Comment by thebrodmann** [comment]
Middlewares in redux don't change the anatomy and functionality of reducers. Action handlers are fundamental reducer portions. So there should not be any direct interaction of the middlewares with action handlers.
A basic example of `deox` with `redux-thunk` could be like below:
```ts
const increment = createAction('INCREMENT');

const incrementAsync = () => dispatch =>
  setTimeout(() => dispatch(increment()), 500);

const root = createReducer(0, handleAction => [
  handleAction(increment, state => state + 1)
]);
```

**Comment by thebrodmann** [comment]
I will close the issue but feel free re-open it.
