### ISSUE TITLE
State in action handler is inferred as DeepImmutableMap<{}, {}>

### ISSUE THREAD

**Issue by Haaxor1689** [thebrodmann/deox#18]
Type of state inside callback of `handle` in `createReducer` in my app is inferred to be an `DeepImmutableMap<{}, {}>` although it should be my concrete type. Here is the code I'm using:

```ts
// Utility.ts
import { createAction as deoxCreateAction } from "deox";
export const createAction = <T>(type: string) => deoxCreateAction(type, r => (v: T) => r(v));

// Actions.ts
import { CodePreviewActionType } from "~/Store/ActionTypes";
import { createAction } from "~/Utility";

export const showCode = createAction<boolean>(CodePreviewActionType.SHOW_CODE);
export const updateCode = createAction<string>(CodePreviewActionType.UPDATE_CODE);

// index.ts
import { createReducer } from "deox";

import * as CodePreviewActions from "./Actions";

export interface CodePreviewState {
    code: string;
    showCode: boolean;
}

const initialState: CodePreviewState = {
    code: "// Insert your code here\n",
    showCode: true,
};

export const codePreviewReducer = createReducer(initialState, handle => [
    // here state is inferred as DeepImmutableMap<{}, {}> although it should be CodePreviewState 
    handle(CodePreviewActions.showCode, (state , { payload: showCode }) => ({
        ...state,
        showCode,
    })),
    handle(CodePreviewActions.updateCode, (state, { payload: code }) => ({
        ...state,
        code,
    })),
]);

export { CodePreviewActions };
```

This also causes the resulting `codePreviewReducer`'s type to be wrong.
Example from usage infers the type correctly.

**Comment by thebrodmann** [comment]
@Haaxor1689 Thank you for your contribution.
According to #3, the state type should be wrap in an immutable data structure type to preventing undesirable mutations.
So in the example that you provided, the desired state type in action handler should be `DeepImmutableObject<CodePreviewState>`.

I had tested the example in the following environment:

- **node**: v11.9.0
- **typescript**: v3.3.3333
- **deox**: v1.1.1

The state type was correct as indicated in the following screenshot.

![Screen Shot 2019-03-15 at 11 41 17 PM](https://user-images.githubusercontent.com/20781126/54459629-766ecb00-477c-11e9-86cd-85183871ebd9.png)

Can you provide more details for repro? Which version of `typescript` and `deox` you are using?

**Comment by Haaxor1689** [comment]
My env is:
- node v10.15.3 (Updating from v8.11.3 didn't help)
- ts v3.3.3
- deox: v1.1.1

Should I declare the `initialState` as `DeepImmutablemap<CodePreviewState>` or where exactly is the type inferred?

**Comment by Haaxor1689** [comment]
Ok I've found where the problem was. I was targeting `es5` in my `tsconfig.json` and therefore he didn't know what `ReadonlyMap` was.

**Comment by thebrodmann** [comment]
> Should I declare the initialState as DeepImmutableMap<CodePreviewState> or where exactly is the type inferred?

No, the initial state type wraps in `Immutable` type by `Reducer` type in deox.
https://github.com/thebrodmann/deox/blob/fcd526553b5a275035d0c55ac6710067938a2439/src/types.ts#L25

> I've also noticed that there is no DeepImmutableMap I can import to use. Is it external type?

No. At least not yet.

> Ok I've found where the problem was. I was targeting es5 in my tsconfig.json and therefore he didn't know what ReadonlyMap was.

Great!
Actually, you aren't forced to change your target option. The problem is lack of type definitions related to `Map` and it can be solved by adding `es2015` to [lib option in tsconfig](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

I think we should mention this in README.md. Can you do that?
