### ISSUE TITLE
Can't export reducer declaration with TSC

### ISSUE THREAD

**Issue by scbird** [thebrodmann/deox#21]
Hi there, thanks for a great library - much better than trying to use react-actions. 

There's an issue when `declaration: true` is set in `tsconfig.json`: attempts to export reducers created by `createReducer()` throws the following error: `TS4023: Exported variable 'reducer' has or is using name 'DeepImmutableArray' from external module "C:/Users/scbird/Documents/Development/pso/node_modules/deox/dist/types" but cannot be named.`

Is it possible to export the DeepImmutable* types so that `createReducer()` can be used in projects that export declaration files?

As a test case, https://github.com/thebrodmann/deox/blob/master/examples/tasks/src/store/tasks.ts fails to compile with `declaration: true`

**Comment by thebrodmann** [comment]
@scbird Hi, I'm so glad that you describe `deox` as a great library. Also, I'm so grateful to you for your contribution.
I think the issue should be fixed in `deox@1.2.1` according to c9d0b3b. If not, feel free to re-open the issue and make me some details.
