### ISSUE TITLE
Usage with redux-thunk

### ISSUE THREAD

**Issue by robertying** [thebrodmann/deox#32]
Hi! Thanks for this awesome library!

I'm new to Redux and had successfully done some work with `redux-thunk` in simple action creators.

However, the `resolve` in `createAction` confuses me. Is it the same `resolve` as in `Promise`, which makes me wonder if I can use async functions in `executor`?

Could you please make an example of how it works with `redux-thunk` or other async action creators?

Thank you!

**Comment by thebrodmann** [comment]
Duplicate of #17

**Comment by thebrodmann** [comment]
I will close the issue for housekeeping purposes. if there is something unclear, feel free to re-open the issue.
